### ISSUE TITLE
like logic

### ISSUE THREAD

**Issue by jujigithub** [jujigithub/nodeLv4#1]
```
router.put("/posts/:postId/like", authMiddleware, async (req, res) => {

  const { postId } = req.params;
  const { userId } = res.locals.user;
  const existLike = await Likes.findOne({
    where: { PostId: postId, UserId: userId },
  });

  try {
    const post = await Posts.findOne({ where: { postId: postId } });
    if (!post) {
      res.status(404).json({ message: "게시글이 존재하지 않습니다." });
      return;
    }

    if (existLike) {
      await Likes.destroy({ where: { PostId: postId } });
      await Posts.update(
        { likes: Sequelize.literal("likes - 1") },
        { where: { postId: postId } }
      );
      res.status(200).json({ message: "게시글의 좋아요를 취소하였습니다." });
    } else {
      await Likes.create({
        PostId: postId,
        UserId: userId,
      });
      await Posts.update(
        { likes: Sequelize.literal("likes + 1") },
        { where: { postId: postId } }
      );
      res.status(200).json({ message: "게시글을 좋아요를 등록하였습니다." });
    }
  } catch (err) {
    console.log(err);
    res.status(400).json({
      errorMessage: "게시글 좋아요에 실패하였습니다.",
    });
  }
});
```
like logic 설명
1. Likes 테이블에서 현재 로그인한 유저(미들웨어 인증을 거친 userId)와 해당유저가 좋아요를 누른 게시글(params값의 postId)을 가져와서 해당 정보를 변수에 담아줌(existLike)
2. 변수가 존재하지 않다면(else구문) 해당 유저가 해당게시글을 누르지 않은 상태이므로 Likes 테이블에 로그인한 유저(userId)와 게시글의 postId값을 생성, Posts테이블의 좋아요 수(likes) 1증가
3. 변수가 존재한다면 이미 해당 게시글을 좋아요 누른 상태이므로 좋아요 취소(Likes의 해당 데이터 삭제), Posts테이블의 좋아요 수(likes) 1감소

고민 사항
1. 처음엔 Likes테이블의 postId 컬럼의 데이터를 조회 및 합산하여 좋아요 수(likes)를 표현하려고 하였으나, 데이터가 많아질 경우 연산이 길어질 것으로 예상되어 좋아요/좋아요취소 시에 바로바로 Posts테이블에 반영되도록 로직을 변경하였습니다.
2. 연산 속도는 개선하였으나 특정 오류(좋아요가 있는상태인데 중복으로 좋아요가 눌린다던지)로 인하여 Posts테이블의 좋아요수가 실제와는 다르게 표시될 위험이 있을거로 예상됨

코드리뷰 요청 사항
1. 로직 구성이 직관적으로 잘 되어있는건지 궁금합니다.
2. 고민 사항에 대한 피드백을 부탁드립니다.
3. 그 외에 개선할 점이 있다면 방향성을 제시해주시면 감사하겠습니다.

**Comment by dana8123** [comment]
1. 잘하셨습니다.
2.` 좋아요가 있는상태인데 중복으로 좋아요가 눌린다던지` 하는 경우는 어떤 경우가 있을까요? 
좋아요 DB에서 정상적으로 조회가 안 된 경우? 그럴 땐 트랜잭션으로 좋아요를 찾는 기능과 post 업데이트 하는 기능을 묶어주면 될 것 같습니다.
3. 좋아요를 계속해서 삭제, 삽입 하는 것 보다는 true, false가 더 낫지않을까요?
